### ISSUE TITLE
Random select delay

### ISSUE THREAD

**Issue by potsmugen** [ikemen-engine/Ikemen-GO#1541]
### Describe the bug

Minor thing but a couple of issues can happen when you mash buttons on random select:
- Selecting more than one of the same character in quick succession
- Large portrait not loading

### To Reproduce

1. Select a team mode with 4 chars
2. Hover to random select
3. Press buttons as fast as you can

### Expected behavior

About the first one I think when a char is selected the random select should advance to the next step.

### Engine Version (or source code date)

0.99

### Operating system

Windows

**Comment by K4thos** [comment]
i think this is already solved in nightly by the commit that changed how randomselct pool works

**Comment by potsmugen** [comment]
I just confirmed that both issues still happen. Easy to check if you select a Simul team of 2 and jam the buttons. Half the time you'll get two of the same char and no big portrait.
I also noticed that you can get duplicate chars even if team duplicates are disabled, which makes it much worse.
