### ISSUE TITLE
Mordakonia slide - He dissapears for a moment when he hits a opponent with his slide.

### ISSUE THREAD

**Issue by FrankSP7ps** [ikemen-engine/Ikemen-GO#1550]
### Describe the bug

So simple history.
I did forget about this little bug for for a year as I didn't touched this boss char for a time.

When I was just checking and seeing what combos I can do with him I did rembember about his slide bug dissapearing on this engine.

As title explain himself, he dissapears for a moment when he hits a opponent with his totally not sub zero reference slide attack.

### To Reproduce

He is another T_N char from the WSMIP Budokai project (a boss for this occasion) soo...
https://www.justnopoint.com/lbends/wsmip/
It should work fine outside of the project just be aware on another him as all the chars of that project requires the common of that project.

(The one of the video is a personal edit of mine that I make him standlone)

Despite of that you should able to reproduce this still.

For use his slide by just hold back + Y and make sure that hits the opponent.

### Expected behavior

When he hits the opponent with his slide, you will see the bug.
For look it better just pause right on the moment.

Compare with mugen 1.1 beta and Ikemen go.

### Screenshots / Video

https://github.com/ikemen-engine/Ikemen-GO/assets/108790388/c02d785b-ba7b-480e-bcf1-cea4f14dae63

### Engine Version (or source code date)

v0.99.0 but as I did forget it, I did discover it on v0.98.2.

### Operating system

None

**Comment by potsmugen** [comment]
This has to do with changing animations during a hitpause, which used to not work in Mugen but apparently was fixed in Mugen 1.1. Ikemen behaves like pre-1.1 currently (which should be fixed, yeah).

A simpler test case for KFM (add to standing light punch):
```
[State 200, ChangeAnim]
type = ChangeAnim
trigger1 = anim = 200
trigger1 = movecontact
value = 230
ignorehitpause = 1
persistent = 0
```

**Comment by FrankSP7ps** [comment]
> "Ikemen behaves like pre-1.1 currently (which should be fixed, yeah)"

Give a quick shot to the most recent nighty build and **nope.**

Is still happening, even with KFM by testing that state that you share.

https://github.com/ikemen-engine/Ikemen-GO/assets/108790388/83bed382-3561-4acd-b72f-9815417046a4

**Comment by potsmugen** [comment]
Oh I meant "should" as in we need to do it, haha. Not as in "it already is".

**Comment by FrankSP7ps** [comment]
> Oh I meant "should" as in we need to do it, haha. Not as in "it already is".

Ah, d'oh.

Then my bad.

My english is still not perfect hehe.
