### ISSUE TITLE
Couple of issues from Tag Mode.

### ISSUE THREAD

**Issue by UrsoManso** [ikemen-engine/Ikemen-GO#2194]
### Describe the bug

1-Characters from Ikaruga have cornerpushback on their moves when a opponent is downed.
2-Intros messing with the camera position in some stages.
3-Characters turning around sometimes when the opponent performs a tag switch.

### To Reproduce

Download the sample character: [Kyo.zip](https://github.com/user-attachments/files/18174186/Kyo.zip)
Replicate the mentioned issues on Nightly's tag mode.

### Screenshots / Video

Pushback issue.

https://github.com/user-attachments/assets/5cde7eeb-1a68-4b42-87c2-547372c9c2a7

Camera issue(only happens in some stages).

https://github.com/user-attachments/assets/1778802e-ec53-4273-b8a0-0d6124b1a7e1

Character turning around during opponent's tag in.

https://github.com/user-attachments/assets/11863b50-92ce-4c1d-9f82-709281717d29

### Engine Version (or source code date)

Nightly

### Operating system

Windows

### Extra context or search terms

The pushback issue wasn't a thing in 0.99.0 from what I remember.

**Comment by potsmugen** [comment]
Please report only one issue per thread so we can close them more easily, but:
1 seems like a character issue. I haven't tested yet but I get the feeling the same would happen in Mugen Simul mode.
2 could indeed be fixed in tag.zss.
3 sounds like same issue as #1755.

**Comment by potsmugen** [comment]
Can you check if 3 still happens in nightly?

**Comment by UrsoManso** [comment]
Sorry for the late reply, but yes, it still happens in Nightly. Also 1 wasn't a thing in 0.99.0.

**Comment by potsmugen** [comment]
Haven't been able to reproduce number 1. Still happening too?

https://github.com/user-attachments/assets/1ca83a0c-f5cc-4986-b21d-a4357e7f67b7

**Comment by UrsoManso** [comment]
Apparently not anymore. I think 1 has been fixed.

**Comment by K4thos** [comment]
Closing since 1 is already fixed, and 3 is a duplicate of a different issue. If 2 is considered a bug, please create a new ticket and upload everything needed to test it (saying "only happens in some stages" is not a sufficient repro step). Also, in the future, please include only one issue per ticket.
