### ISSUE TITLE
Better controller support on linux is needed

### ISSUE THREAD

**Issue by SandWoodJones** [ikemen-engine/Ikemen-GO#258]
I'm using Arch Linux, and been having problems with setting up Ikemen-Go to use my DS4 controller.
First of all, I can't change the controller configuration through the in-game joystick config GUI as it doesn't capture any input from my controller, making me unable to edit it.
To fix this, I had to use `jstest` to get the ID number of each button and then manually map it to the config.json file. This also had problems since I couldn't figure out the ID numbers for the joystick and the D-Pad as they're axis, not buttons. Strangely enough the only movement I could get was moving left, by pressing Up on the D-Pad.
Then I decided to just add the game to my steam library as a non-steam game and use its built-in controller remapping, mapping each button and axis to a keyboard key.
This works, but it's not perfect nor optimal.

**Comment by ssj17vegeta** [comment]
Can confirm the current version is somewhat broken in terms of controller support (Ubuntu 21.04 here).

Plugging-in a Madcatz XBox controller crashes the program on startup and outputs this in the console :
`GLFW: An uncaught error has occurred: InvalidValue: Invalid button in gamepad mapping 050000005e040000fd02000003090000 (Xbox One Wireless Controller)
GLFW: Please report this bug in the Go package immediately.`

Though it seems that error is being investigated here : https://github.com/go-gl/glfw/issues/292

Plugging in a standard wired XBox 360 controller outputs no error, but the controls are completely non-responsive : D-Pad up and down are mixed up in the main menu, and I cannot input any buttons when configuring the controller in the options menu.

Will definitely try the steam mapping tomorrow as a workaround though :)

**Comment by Orochikyocr** [comment]
Can confirm this. 
Qanba Cristal Clear and Generic PS3 sticks which both works on windows doesn't not work on Linux in the config input menu.
Also DS4, PS3 and my Bluetooth Marvo Gt62 controller doesn't work in the config menu.
All of them work if I configure them directly from the config.json.

**Comment by ssj17vegeta** [comment]
It seems the problem I was talking about has been fixed 15 days ago, and will be integrated in 3.3.5. There's hope :)

Also tried to fiddle with config.json to no avail : buttons are registered OK, but the it seems the D-Pad axes are considered buttons instead of axes so... yah :(

**Comment by SeongGino** [comment]
Huh, so I'm not the only one who noticed.
Tried with two different Xinput gamepads; neither register in the config menu, despite working enough to navigate to said menu.

**Comment by Orochikyocr** [comment]
Yes, 0.98, my sticks are still broken. Ps3 and xbox 360 one. My generic Marvo Controller works out of the box.

**Comment by ssvb** [comment]
The [joysticks](https://github.com/glfw/glfw/blob/master/tests/joysticks.c) test program from https://github.com/glfw/glfw shows the following for my PS3 controller in Linux in an idle state (no buttons are pressed):
![ps3_idle_state](https://user-images.githubusercontent.com/78642/183241854-f84cc236-26da-4e5d-9168-7d6331442a27.png)

The sliders in the leftmost state (highlighted by the arrows) correspond to L2/R2 analog buttons of the PS3 controller. If I slowly press these buttons, then the sliders gradually move to the right and reach the rightmost side when the buttons are fully pressed.

Now how is all of this is related to broken joystick config in Ikemen-GO? The code at https://github.com/ikemen-engine/Ikemen-GO/blob/0.98.2/src/script.go#L1291-L1335 checks the joystick button state when configuring the joystick. In an idle PS3 controller state with no buttons pressed, the array `axes` typically looks like `[-0.0039215684 0.027451038 -1 0.011764765 -0.035294116 -1]`. The elements with indexes 2 and 5 contain `-1`, which is interpreted by the code as if some of the buttons are always pressed (the return value is "-11"). And then this return value is used by code at https://github.com/ikemen-engine/Ikemen-GO/blob/0.98.2/external/script/options.lua#L1754-L1761, which expects to see that some joystick button gets pressed and then all buttons are released. If it can never see that all buttons are released, then it can't work properly.

I have a pull request with a fix for my PS3 controller: https://github.com/ikemen-engine/Ikemen-GO/pull/629. The other controllers probably fail because of something similar. But I wonder why people are not complaining about Windows? Also the code seems to already have some special handling for xbox 360 controller and yet people reported problems with it in Linux.
