### ISSUE TITLE
Movelist [<-/->] rendering regression in commit aff9383b25ebc344b3f0310271a6f4e29a51cf5b

### ISSUE THREAD

**Issue by ssvb** [ikemen-engine/Ikemen-GO#635]
Take a look at the movelist of Kung Fu Man in the game:

Good (Ikemen-GO ~v0.98.0~ v0.98.2):
![movelist_good](https://user-images.githubusercontent.com/78642/183828903-eab79391-d97e-459e-8e33-142e37a89d6f.png)
Bad (Ikemen-GO ~v0.98.2~ git master):
![movelist_bad](https://user-images.githubusercontent.com/78642/183828893-405ca5fe-4718-45c9-9e63-4f46ef648980.png)

Bisecting reveals the problematic commit:
```
aff9383b25ebc344b3f0310271a6f4e29a51cf5b is the first bad commit
commit aff9383b25ebc344b3f0310271a6f4e29a51cf5b
Author: Sam Hocevar <sam@hocevar.net>
Date:   Mon Mar 7 16:16:25 2022 +0100

    Avoid a string replace call in the text printing code

 src/font.go | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
```
Reverting aff9383b25ebc344b3f0310271a6f4e29a51cf5b in master fixes the problem.

**Comment by K4thos** [comment]
this is already fixed in latest github build

**Comment by ssvb** [comment]
How can I confirm the fix? The newly pushed commit 6ad0ee86c6c43736311cc6c00802ba825a13f806 does not help.

**Comment by ssvb** [comment]
Hmm, the v0.98.2 build was released before this regression. I have updated the first comment in the bugreport.

**Comment by K4thos** [comment]
linked commit is unrelated, it should be fixed for few weeks now (or at least it doesn't happen to me anymore on windows), The change that fixes it was done scripts iirc.
![ikemen000](https://user-images.githubusercontent.com/8928195/183867929-54cf855f-af6f-4f8a-926c-c8bbf17afc33.png)
![ikemen001](https://user-images.githubusercontent.com/8928195/183867935-0f91f6fb-cdc6-4b89-8e47-23b9105948af.png)

**Comment by K4thos** [comment]
try downloading latest screenpack files: https://github.com/ikemen-engine/Ikemen_GO-Elecbyte-Screenpack
may have been related to this compatibility fix (not sure) https://github.com/ikemen-engine/Ikemen-GO/commit/573707f4a3be29b09d14889645c052e3eb48c22c

**Comment by ssvb** [comment]
I'm still reproducing the bug in both Linux and Windows after cloning https://github.com/ikemen-engine/Ikemen-GO https://github.com/ikemen-engine/Ikemen-GO/commit/6ad0ee86c6c43736311cc6c00802ba825a13f806 and https://github.com/ikemen-engine/Ikemen_GO-Elecbyte-Screenpack/commit/324dfc956f1e95a8bd5b49707c25a842c2f8ed2e from git, combining sources and screenpack in the same directory, compiling Ikemen-GO and running it (Kung Fu Man vs. Kung Fu Man in arcade mode). It's a clean test, there are no other files (even no custom edits or changes in the config file). Go version is 1.17 in Linux and 1.19 in Windows.

**Comment by K4thos** [comment]
ah, ok, now I remember. The bug was in glfont library. It's fixed here: https://github.com/ikemen-engine/glfont

**Comment by ssvb** [comment]
Now it works fine. Thanks! Would it be possible to update `go.mod` in git to include the glfont fix?
